[[plugins]]
repository = 'shougo/neomru.vim'

[[plugins]]
repository = 'thinca/vim-quickrun' 

[[plugins]]
repository = 'itchyny/lightline.vim'

[[plugins]]
repository = 'sudo.vim'

[[plugins]]
repository = "kana/vim-tabpagecd"

[[plugins]]
repository = 'itchyny/landscape.vim'

[[plugins]]
repository = "rhysd/clever-f.vim"

[[plugins]]
repository = "Shougo/echodoc"

[[plugins]]
repository = "tyru/caw.vim"

[[plugins]]
repository = "shougo/tabpagebuffer.vim"

[[plugins]]
repository = 'surround.vim'

