[[plugins]]
repository = 'shougo/neomru.vim'

[[plugins]]
repository = 'shougo/denite.nvim'

[[plugins]]
repository = 'thinca/vim-quickrun' 
[[plugins]]
repository = 'itchyny/lightline.vim'

[[plugins]]
repository = 'sudo.vim'

[[plugins]]
repository = "kana/vim-tabpagecd"

[[plugins]]
repository = 'itchyny/landscape.vim'

[[plugins]]
repository = "rhysd/clever-f.vim"

[[plugins]]
repository = "Shougo/echodoc"

[[plugins]]
repository = "tyru/caw.vim"

[[plugins]]
repository = "shougo/tabpagebuffer.vim"

[[plugins]]
repository = 'surround.vim'

[[plugins]]
repository = "vim-jp/vim-go-extra"

[[plugins]]
repository = 'kannokanno/previm'

[[plugins]]
repository = 'tyru/open-browser.vim'

[[plugins]]
repository = 'cisco.vim'

[[plugins]]
repository = 'momota/cisco.vim'

[[plugins]]
repository = 'momota/junos.vim'

[[plugins]]
repository = 'mattn/benchvimrc-vim'

[[plugins]]
repository = 'thinca/vim-visualstar'

[[plugins]]
repository = 'Shougo/unite-outline'

[[plugins]]
repository = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repository = 'roxma/nvim-yarp'

[[plugins]]
repository = 'Shougo/deoplete.nvim'

[[plugins]]
repository = 'ujihisa/vimshell-ssh'

[[plugins]]
repository = 'github/copilot.vim'

[[plugins]]
repository = 'deoplete-plugins/deoplete-zsh'

[[plugins]]
repository = 'Shougo/deol.nvim'

[[plugins]]
repository = 'Shougo/vimproc.vim'
 
  [plugins.build]
  windows = 'tools\\update-dll-mingw'
  cygwin = 'make -f make_cygwin.mak'
  mac = 'make -f make_mac.mak'
  unix = 'make -f make_unix.mak'

